import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href={inter.cssHref} />
      </Head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default RootLayout;
